// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_spend_arc/hive/hive_adapters.dart';
import 'package:flutter_spend_arc/main.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetModelAdapter());
    registerAdapter(BudgetModelAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BudgetModelAdapter());
    registerAdapter(BudgetModelAdapter());
    registerAdapter(TransactionModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}
